let stateOptions = [{value:'ACT', label:'Australian Capital Territory'},
{value:'NSW', label:'New South Wales'},
{value:'NT', label:'Northern Territory'},
{value:'N', label:'New Zealand'},
{
    value:'OS',
    label:'Overseas (except Other States or Territories of Australia or New Zealand)'},
{
    value:'OTH',
    label :'Other State or Territory of Australia (Norfolk Island, value:Australian Antarctic Territory, value:...)'},
{value:'QLD', label:'Queensland'},
{value:'SA', label:'South Australia'},
{value:'TAS', label:'Tasmania'},
{value:'VIC', label:'Victoria'},
{value:'WA', label:'Western Australia'}];

let streetTypeOptions = [
    {value:'ACCS', label:'Access'},
    {value:'ALLY', label:'Alley'},
    {value:'ALWY', label:'Alleyway'},
    {value:'AMBL', label:'Amble'},
    {value:'ANCG', label:'Anchorage'},
    {value:'APP', label:'Approach'},
    {value:'ARC', label:'Arcade'},
    {value:'ART', label:'Artery'},
    {value:'AVE', label:'Avenue'},
    {value:'BASN', label:'Basin'},
    {value:'BCH', label:'Beach'},
    {value:'BEND', label:'Bend'},
    {value:'BLK', label:'Block'},
    {value:'BVD', label:'Boulevard'},
    {value:'BRCE', label:'Brace'},
    {value:'BRAE', label:'Brae'},
    {value:'BRK', label:'Break'},
    {value:'BDGE', label:'Bridge'},
    {value:'BDWY', label:'Broadway'},
    {value:'BROW', label:'Brow'},
    {value:'BYPA', label:'Bypass'},
    {value:'BYWY', label:'Byway'},
    {value:'CAUS', label:'Causeway'},
    {value:'CTR', label:'Centre'},
    {value:'CNWY', label:'Centreway'},
    {value:'CH', label:'Chase'},
    {value:'CIR', label:'Circle'},
    {value:'CLT', label:'Circlet'},
    {value:'CCT', label:'Circuit'},
    {value:'CRCS', label:'Circus'},
    {value:'CL', label:'Close'},
    {value:'CLDE', label:'Colonnade'},
    {value:'CMMN', label:'Common'},
    {value:'CON', label:'Concourse'},
    {value:'CPS', label:'Copse'},
    {value:'CNR', label:'Corner'},
    {value:'CSO', label:'Corso'},
    {value:'CT', label:'Court'},
    {value:'CTYD', label:'Courtyard'},
    {value:'COVE', label:'Cove'},
    {value:'CRES', label:'Crescent'},
    {value:'CRST', label:'Crest'},
    {value:'CRSS', label:'Cross'},
    {value:'CRSG', label:'Crossing'},
    {value:'CRD', label:'Crossroad'},
    {value:'COWY', label:'Crossway'},
    {value:'CUWY', label:'Cruiseway'},
    {value:'CDS', label:'Cul-de-sac'},
    {value:'CTTG', label:'Cutting'},
    {value:'DALE', label:'Dale'},
    {value:'DELL', label:'Dell'},
    {value:'DEVN', label:'Deviation'},
    {value:'DIP', label:'Dip'},
    {value:'DSTR', label:'Distributor'},
    {value:'DR', label:'Drive'},
    {value:'DRWY', label:'Driveway'},
    {value:'EDGE', label:'Edge'},
    {value:'ELB', label:'Elbow'},
    {value:'END', label:'End'},
    {value:'ENT', label:'Entrance'},
    {value:'ESP', label:'Esplanade'},
    {value:'EST', label:'Estate'},
    {value:'EXP', label:'Expressway'},
    {value:'EXTN', label:'Extension'},
    {value:'FAWY', label:'Fairway'},
    {value:'FTRK', label:'Fire Track'},
    {value:'FITR', label:'Fire Trail'},
    {value:'FLAT', label:'Flat'},
    {value:'FOLW', label:'Follow'},
    {value:'FTWY', label:'Footway'},
    {value:'FSHR', label:'Foreshore'},
    {value:'FORM', label:'Formation'},
    {value:'FWY', label:'Freeway'},
    {value:'FRNT', label:'Front'},
    {value:'FRTG', label:'Frontage'},
    {value:'GAP', label:'Gap'},
    {value:'GDN', label:'Garden'},
    {value:'GDNS', label:'Gardens'},
    {value:'GTE', label:'Gate'},
    {value:'GTES', label:'Gates'},
    {value:'GLD', label:'Glade'},
    {value:'GLEN', label:'Glen'},
    
    {value:'GRA', label:'Grange'},
    {value:'GRN', label:'Green'},
    {value:'GRND', label:'Ground'},
    {value:'GR', label:'Grove'},
    {value:'GLY', label:'Gully'},
    {value:'HTS', label:'Heights'},
    {value:'HRD', label:'Highroad'},
    {value:'HWY', label:'Highway'},
    {value:'HILL', label:'Hill'},
    {value:'INTG', label:'Interchange'},
    {value:'INTN', label:'Intersection'},
    {value:'JNC', label:'Junction'},
    {value:'KEY', label:'Key'},
    {value:'LDG', label:'Landing'},
    {value:'LANE', label:'Lane'},
    {value:'LNWY', label:'Laneway'},
    {value:'LEES', label:'Lees'},
    {value:'LNE', label:'Line'},
    {value:'LINK', label:'Link'},
    {value:'LT', label:'Little'},
    {value:'LKT', label:'Lookout'},
    {value:'LOOP', label:'Loop'},
    {value:'LWR', label:'Lower'},
    {value:'MALL', label:'Mall'},
    {value:'MNDR', label:'Meander'},
    {value:'MEW', label:'Mew'},
    {value:'MEWS', label:'Mews'},
    {value:'MWY', label:'Motorway'},
    {value:'MT', label:'Mount'},
    {value:'NOOK', label:'Nook'},
    {value:'OTLK', label:'Outlook'},
    {value:'PDE', label:'Parade'},
    {value:'PARK', label:'Park'},
    {value:'PKLD', label:'Parklands'},
    {value:'PKWY', label:'Parkway'},
    {value:'PART', label:'Part'},
    {value:'PASS', label:'Pass'},
    {value:'PATH', label:'Path'},
    {value:'PHWY', label:'Pathway'},
    {value:'PIAZ', label:'Piazza'},
    {value:'PL', label:'Place'},
    
    {value:'PLAT', label:'Plateau'},
    {value:'PLZA', label:'Plaza'},
    {value:'PKT', label:'Pocket'},
    {value:'PNT', label:'Point'},
    {value:'PORT', label:'Port'},
    {value:'PROM', label:'Promenade'},
    {value:'QUAD', label:'Quad'},
    {value:'QDGL', label:'Quadrangle'},
    {value:'QDRT', label:'Quadrant'},
    {value:'QY', label:'Quay'},
    {value:'QYS', label:'Quays'},
    {value:'RMBL', label:'Ramble'},
    {value:'RAMP', label:'Ramp'},
    {value:'RNGE', label:'Range'},
    {value:'RCH', label:'Reach'},
    {value:'RES', label:'Reserve'},
    {value:'REST', label:'Rest'},
    {value:'RTT', label:'Retreat'},
    {value:'RIDE', label:'Ride'},
    {value:'RDGE', label:'Ridge'},
    {value:'RGWY', label:'Ridgeway'},
    {value:'ROWY', label:'Right of Way'},
    {value:'RING', label:'Ring'},
    {value:'RISE', label:'Rise'},
    {value:'RVR', label:'River'},
    {value:'RVWY', label:'Riverway'},
    {value:'RVRA', label:'Riviera'},
    {value:'RD', label:'Road'},
    {value:'RDS', label:'Roads'},
    {value:'RDSD', label:'Roadside'},
    {value:'RDWY', label:'Roadway'},
    {value:'RNDE', label:'Ronde'},
    {value:'RSBL', label:'Rosebowl'},
    {value:'RTY', label:'Rotary'},
    {value:'RND', label:'Round'},
    {value:'RTE', label:'Route'},
    {value:'ROW', label:'Row'},
    {value:'RUE', label:'Rue'},
    {value:'RUN', label:'Run'},
    {value:'SWY', label:'Service Way'},
    {value:'SDNG', label:'Siding'},
    
    {value:'SLPE', label:'Slope'},
    {value:'SND', label:'Sound'},
    {value:'SPUR', label:'Spur'},
    {value:'SQ', label:'Square'},
    {value:'STRS', label:'Stairs'},
    {value:'SHWY', label:'State Highway'},
    {value:'STPS', label:'Steps'},
    {value:'STRA', label:'Strand'},
    {value:'ST', label:'Street'},
    {value:'STRP', label:'Strip'},
    {value:'SBWY', label:'Subway'},
    {value:'TARN', label:'Tarn'},
    {value:'TCE', label:'Terrace'},
    {value:'THOR', label:'Thoroughfare'},
    {value:'TLWY', label:'Tollway'},
    {value:'TOP', label:'Top'},
    {value:'TOR', label:'Tor'},
    {value:'TWRS', label:'Towers'},
    {value:'TRK', label:'Track'},
    {value:'TRL', label:'Trail'},
    {value:'TRLR', label:'Trailer'},
    {value:'TRI', label:'Triangle'},
    {value:'TKY', label:'Trunkway'},
    {value:'TURN', label:'TURN'},
    {value:'UPAS', label:'Underpass'},
    {value:'UPR', label:'Upper'},
    {value:'VALE', label:'Vale'},
    {value:'VDCT', label:'Viaduct'},
    {value:'VIEW', label:'View'},
    {value:'VLLS', label:'Villas'},
    {value:'VSTA', label:'Vista'},
    {value:'WADE', label:'Wade'},
    {value:'WALK', label:'Walk'},
    {value:'WKWY', label:'Walkway'},
    {value:'WAY', label:'Way'},
    {value:'WHRF', label:'Wharf'},
    {value:'WYND', label:'Wynd'},
    {value:'YARD', label:'Yard'}
];
let countryOptions = [
    { value:'AUS', label:'Australia'},
    { value:'AFG', label:'Afghanistan'},
    { value:'ALA', label:'Aland Islands'},
    { value:'ALB', label:'Albania'},
    { value:'DZA', label:'Algeria'},
    { value:'ASM', label:'American Samoa'},
    { value:'AND', label:'Andorra'},
    { value:'AGO', label:'Angola'},
    { value:'AIA', label:'Anguilla'},
    { value:'ATA', label:'Antarctica'},
    { value:'ATG', label:'Antigua and Barbuda'},
    { value:'ARG', label:'Argentina'},
    { value:'ARM', label:'Armenia'},
    { value:'ABW', label:'Aruba'},
    { value:'AUT', label:'Austria'},
    { value:'AZE', label:'Azerbaijan'},
    { value:'BHS', label:'Bahamas'},
    { value:'BHR', label:'Bahrain'},
    { value:'BGD', label:'Bangladesh'},
    { value:'BRB', label:'Barbados'},
    { value:'BLR', label:'Belarus'},
    { value:'BEL', label:'Belgium'},
    { value:'BLZ', label:'Belize'},
    { value:'BEN', label:'Benin'},
    { value:'BMU', label:'Bermuda'},
    { value:'BTN', label:'Bhutan'},
    { value:'BOL', label:'Bolivia'},
    { value:'BIH', label:'Bosnia and Herzegovina'},
    { value:'BWA', label:'Botswana'},
    { value:'BVT', label:'Bouvet Island'},
    { value:'BRA', label:'Brazil'},
    { value:'VGB', label:'British Virgin Islands'},
    { value:'IOT', label:'British Indian Ocean Territory'},
    { value:'BRN', label:'Brunei Darussalam'},
    { value:'BGR', label:'Bulgaria'},
    { value:'BFA', label:'Burkina Faso'},
    { value:'BDI', label:'Burundi'},
    { value:'KHM', label:'Cambodia'},
    { value:'CMR', label:'Cameroon'},
    { value:'CAN', label:'Canada'},
    { value:'CPV', label:'Cape Verde'},
    { value:'CYM', label:'Cayman Islands'},
    { value:'CAF', label:'Central African Republic'},
    { value:'TCD', label:'Chad'},
    { value:'CHL', label:'Chile'},
    { value:'CHN', label:'China'},
    { value:'HKG', label:'Hong Kong'},
    { value:'MAC', label:'Macao'},
    { value:'CXR', label:'Christmas Island'},
    { value:'CCK', label:'Cocos'},
    { value:'COL', label:'Colombia'},
    { value:'COM', label:'Comoros'},
    { value:'COG', label:'Congo (Brazzaville)'},
    { value:'COD', label:'Congo, value:Democratic Republic of the'},
    { value:'COK', label:'Cook Islands'},
    { value:'CRI', label:'Costa Rica'},
    { value:'CIV', label:'Côte d\'Ivoire'},
    { value:'HRV', label:'Croatia'},
    { value:'CUB', label:'Cuba'},
    { value:'CYP', label:'Cyprus'},
    { value:'CZE', label:'Czech Republic'},
    { value:'DNK', label:'Denmark'},
    { value:'DJI', label:'Djibouti'},
    { value:'DMA', label:'Dominica'},
    { value:'DOM', label:'Dominican Republic'},
    { value:'ECU', label:'Ecuador'},
    { value:'EGY', label:'Egypt'},
    { value:'SLV', label:'El Salvador'},
    { value:'GNQ', label:'Equatorial Guinea'},
    { value:'ERI', label:'Eritrea'},
    { value:'EST', label:'Estonia'},
    { value:'ETH', label:'Ethiopia'},
    { value:'FLK', label:'Falkland Islands (Malvinas)'},
    { value:'FRO', label:'Faroe Islands'},
    { value:'FJI', label:'Fiji'},
    { value:'FIN', label:'Finland'},
    { value:'FRA', label:'France'},
    { value:'GUF', label:'French Guiana'},
    { value:'PYF', label:'French Polynesia'},
    { value:'ATF', label:'French Southern Territories'},
    { value:'GAB', label:'Gabon'},
    { value:'GMB', label:'Gambia'},
    { value:'GEO', label:'Georgia'},
    { value:'DEU', label:'Germany'},
    { value:'GHA', label:'Ghana'},
    { value:'GIB', label:'Gibraltar'},
    { value:'GRC', label:'Greece'},
    { value:'GRL', label:'Greenland'},
    { value:'GRD', label:'Grenada'},
    { value:'GLP', label:'Guadeloupe'},
    { value:'GUM', label:'Guam'},
    { value:'GTM', label:'Guatemala'},
    { value:'GGY', label:'Guernsey'},
    { value:'GIN', label:'Guinea'},
    { value:'GNB', label:'Guinea-Bissau'},
    { value:'GUY', label:'Guyana'},
    { value:'HTI', label:'Haiti'},
    { value:'HMD', label:'Heard Island and Mcdonald Islands'},
    { value:'VAT', label:'Holy See (Vatican City State)'},
    { value:'HND', label:'Honduras'},
    { value:'HUN', label:'Hungary'},
    { value:'ISL', label:'Iceland'},
    { value:'IND', label:'India'},
    { value:'IDN', label:'Indonesia'},
    { value:'IRN', label:'Iran, value:Islamic Republic of'},
    { value:'IRQ', label:'Iraq'},
    { value:'IRL', label:'Ireland'},
    { value:'IMN', label:'Isle of Man'},
    { value:'ISR', label:'Israel'},
    { value:'ITA', label:'Italy'},
    { value:'JAM', label:'Jamaica'},
    { value:'JPN', label:'Japan'},
    { value:'JEY', label:'Jersey'},
    { value:'JOR', label:'Jordan'},
    { value:'KAZ', label:'Kazakhstan'},
    { value:'KEN', label:'Kenya'},
    { value:'KIR', label:'Kiribati'},
    { value:'PRK', label:'Korea, value:Democratic People\'s Republic of'},
    { value:'KOR', label:'Korea, value:Republic of'},
    { value:'KWT', label:'Kuwait'},
    { value:'KGZ', label:'Kyrgyzstan'},
    { value:'LAO', label:'Lao PDR'},
    { value:'LVA', label:'Latvia'},
    { value:'LBN', label:'Lebanon'},
    { value:'LSO', label:'Lesotho'},
    { value:'LBR', label:'Liberia'},
    { value:'LBY', label:'Libya'},
    { value:'LIE', label:'Liechtenstein'},
    { value:'LTU', label:'Lithuania'},
    { value:'LUX', label:'Luxembourg'},
    { value:'MKD', label:'Macedonia, value:Republic of'},
    { value:'MDG', label:'Madagascar'},
    { value:'MWI', label:'Malawi'},
    { value:'MYS', label:'Malaysia'},
    { value:'MDV', label:'Maldives'},
    { value:'MLI', label:'Mali'},
    { value:'MLT', label:'Malta'},
    { value:'MHL', label:'Marshall Islands'},
    { value:'MTQ', label:'Martinique'},
    { value:'MRT', label:'Mauritania'},
    { value:'MUS', label:'Mauritius'},
    { value:'MYT', label:'Mayotte'},
    { value:'MEX', label:'Mexico'},
    { value:'FSM', label:'Micronesia, value:Federated States of'},
    { value:'MDA', label:'Moldova'},
    { value:'MCO', label:'Monaco'},
    { value:'MNG', label:'Mongolia'},
    { value:'MNE', label:'Montenegro'},
    { value:'MSR', label:'Montserrat'},
    { value:'MAR', label:'Morocco'},
    { value:'MOZ', label:'Mozambique'},
    { value:'MMR', label:'Myanmar'},
    { value:'NAM', label:'Namibia'},
    { value:'NRU', label:'Nauru'},
    { value:'NPL', label:'Nepal'},
    { value:'NLD', label:'Netherlands'},
    { value:'ANT', label:'Netherlands Antilles'},
    { value:'NCL', label:'New Caledonia'},
    { value:'NZL', label:'New Zealand'},
    { value:'NIC', label:'Nicaragua'},
    { value:'NER', label:'Niger'},
    { value:'NGA', label:'Nigeria'},
    { value:'NIU', label:'Niue'},
    { value:'NFK', label:'Norfolk Island'},
    { value:'MNP', label:'Northern Mariana Islands'},
    { value:'NOR', label:'Norway'},
    { value:'OMN', label:'Oman'},
    { value:'PAK', label:'Pakistan'},
    { value:'PLW', label:'Palau'},
    { value:'PSE', label:'Palestinian Territory, value:Occupied'},
    { value:'PAN', label:'Panama'},
    { value:'PNG', label:'Papua New Guinea'},
    { value:'PRY', label:'Paraguay'},
    { value:'PER', label:'Peru'},
    { value:'PHL', label:'Philippines'},
    { value:'PCN', label:'Pitcairn'},
    { value:'POL', label:'Poland'},
    { value:'PRT', label:'Portugal'},
    { value:'PRI', label:'Puerto Rico'},
    { value:'QAT', label:'Qatar'},
    { value:'REU', label:'Réunion'},
    { value:'ROU', label:'Romania'},
    { value:'RUS', label:'Russian Federation'},
    { value:'RWA', label:'Rwanda'},
    { value:'BLM', label:'Saint-Barthélemy'},
    { value:'SHN', label:'Saint Helena'},
    { value:'KNA', label:'Saint Kitts and Nevis'},
    { value:'LCA', label:'Saint Lucia'},
    { value:'MAF', label:'Saint-Martin (French part)'},
    { value:'SPM', label:'Saint Pierre and Miquelon'},
    { value:'VCT', label:'Saint Vincent and Grenadines'},
    { value:'WSM', label:'Samoa'},
    { value:'SMR', label:'San Marino'},
    { value:'STP', label:'Sao Tome and Principe'},
    { value:'SAU', label:'Saudi Arabia'},
    { value:'SEN', label:'Senegal'},
    { value:'SRB', label:'Serbia'},
    { value:'SYC', label:'Seychelles'},
    { value:'SLE', label:'Sierra Leone'},
    { value:'SGP', label:'Singapore'},
    { value:'SVK', label:'Slovakia'},
    { value:'SVN', label:'Slovenia'},
    { value:'SLB', label:'Solomon Islands'},
    { value:'SOM', label:'Somalia'},
    { value:'ZAF', label:'South Africa'},
    { value:'SGS', label:'South Georgia and the South Sandwich Islands'},
    { value:'SSD', label:'South Sudan'},
    { value:'ESP', label:'Spain'},
    { value:'LKA', label:'Sri Lanka'},
    { value:'SDN', label:'Sudan'},
    { value:'SUR', label:'Suriname *'},
    { value:'SJM', label:'Svalbard and Jan Mayen Islands'},
    { value:'SWZ', label:'Swaziland'},
    { value:'SWE', label:'Sweden'},
    { value:'CHE', label:'Switzerland'},
    { value:'SYR', label:'Syrian Arab Republic (Syria)'},
    { value:'TWN', label:'Taiwan, value:Republic of China'},
    { value:'TJK', label:'Tajikistan'},
    { value:'TZA', label:'Tanzania *, value:United Republic of'},
    { value:'THA', label:'Thailand'},
    { value:'TLS', label:'Timor-Leste'},
    { value:'TGO', label:'Togo'},
    { value:'TKL', label:'Tokelau'},
    { value:'TON', label:'Tonga'},
    { value:'TTO', label:'Trinidad and Tobago'},
    { value:'TUN', label:'Tunisia'},
    { value:'TUR', label:'Turkey'},
    { value:'TKM', label:'Turkmenistan'},
    { value:'TCA', label:'Turks and Caicos Islands'},
    { value:'TUV', label:'Tuvalu'},
    { value:'UGA', label:'Uganda'},
    { value:'UKR', label:'Ukraine'},
    { value:'ARE', label:'United Arab Emirates'},
    { value:'GBR', label:'United Kingdom'},
    { value:'USA', label:'United States of America'},
    { value:'UMI', label:'United States Minor Outlying Islands'},
    { value:'URY', label:'Uruguay'},
    { value:'UZB', label:'Uzbekistan'},
    { value:'VUT', label:'Vanuatu'},
    { value:'VEN', label:'Venezuela (Bolivarian Republic of)'},
    { value:'VNM', label:'Viet Nam'},
    { value:'VIR', label:'Virgin Islands, value:US'},
    { value:'WLF', label:'Wallis and Futuna Islands'},
    { value:'ESH', label:'Western Sahara'},
    { value:'YEM', label:'Yemen'},
    { value:'ZMB', label:'Zambia'},
    { value:'ZWE', label:'Zimbabwe'}]
let atOptions = [
        {value:'AL', label:'Auto Loan'},
        {value:'CC', label:'Continuing Credit Contract'},
        {value:'CA', label:'Charge Card'},
        {value:'OD', label:'Overdraft'},
        {value:'PF', label:'Personal Loan (fixed term)'},
        {value:'PR', label:'Personal Loan (revolving)'},
        {value:'RE', label:'Equipment Hire or Rental'},
        {value:'RM', label:'Real Property Mortgage'},
        {value:'TC', label:'Telecommunications Services'},
        {value:'UA', label:'Utilities'},
        {value:'AO', label:'All Other Account Types'}];
let picklistMap = {
    atOptions, countryOptions, streetTypeOptions, stateOptions
}
export default picklistMap;