public class MacquarieConstants {
    
    public static final Integer STATUS_OK = 200;
    public static final Integer STATUS_REQUEST_VALIDATE = 400;
    public static final Integer STATUS_INTERNAL_ERROR = 510;
    public static final Integer STATUS_NOT_AUTHORIZED = 401;
    public static final Integer STATUS_UNAUTHORIZED_ACCESS = 403;
    public static final Integer STATUS_ENTITY_NOT_FOUND = 404;
    
    public static final String BEARER = 'Bearer ';
    public static final String ACCESS_TOKEN = 'access_token';
    public static final String AUTHORIZATION = 'Authorization';
    
    public static final String DOMAIN_ASSET_TYPE = 'ASSET_TYPE';
    public static final String LOAN_FREQUENCY = 'FREQUENCY_LOAN';
    
    public static final String TYPE_PERCENTAGE = 'Percentage';
    public static final String TYPE_VALUE = 'Value';

}