public class PepperConstants {
    
    public static final String WEEKLY = 'Weekly';
    public static final String FORTNIGHTLY = 'Fortnightly';
    public static final String MONTHLY = 'Monthly';
    public static final String COUNTRYCODE = 'AUS';
    
    public static String SOLVE_BROKERAGE_AMOUNT = 'SOLVE_BROKERAGE_AMOUNT';
    
    public static final String AUTHORIZATION = 'Authorization';

    // Lelo
    public static final String ADDRESS_FORMAT_STANDARD = 'Standard';
    public static final String ADDRESS_FORMAT_NONSTANDARD = 'Non Standard';
    public static final String ADDRESS_INT_STATE = 'INT';

    public static final String EMPLOYMENT_STATUS_CURRENT = 'Current';
    public static final String EMPLOYMENT_STATUS_PREVIOUS = 'Previous';

    public static final String OWNER_PRIMARY = 'Primary';
    public static final String OWNER_COBORROWER = 'Co-borrower';
    public static final String OWNER_JOINT = 'Joint';
    // Liabilities
    public static final String LIABILITY_MORTGAGE = 'Mortgage';
    public static final String LIABILITY_PL = 'Loan';
    public static final String LIABILITY_CREDITCARD = 'Card';
    public static final String LIABILITY_OVERDRAF = 'Overdraft';
    public static final String LIABILITY_ASSET = 'MotorVehicleLoan';
    public static final String LIABILITY_OTHER = 'Other';
    // Expenses
    public static final String EXPENSE_BASIC = 'Basic';
    public static final String EXPENSE_CLOTHING = 'Clothing';
    public static final String EXPENSE_UTILITIES = 'Utilities';
    public static final String EXPENSE_ENTERTAINMENT = 'Entertainment';
    public static final String EXPENSE_TRAVEL = 'Travel';
    public static final String EXPENSE_FEES = 'Fees';
    public static final String EXPENSE_VEHICLEINSURANCE = 'VehicleInsurance';
    // Other Expenses
    public static final String EXPENSE_HOUSING = 'Housing';
    public static final String EXPENSE_OTHER = 'Other';
    public static final String ACCEPT = 'Accept';
    public static final Integer STATUS_OK = 200;
}