public class PPSRProxyRequest extends ObjectJsonSerialize{
    
    public String typeSearchSerialNumber {set; get;}
    
    public String serialNumber {set; get;}
    
    public String soapEndpointUrl {set; get;}
    
    public String environment {set; get;}
    
    public String userName {set; get;}
    
    public String password {set; get;}
    
    public String nonce {set; get;}
    
    public String created {set; get;}
    
    public String emailAddress {set; get;}
    
    public String oppId {set; get;}

}