public class PPSRServiceManager extends APIServiceManager{
    
    public static String T_FALSE = 'false';
    public static String T_TRUE = 'true';
    
    public static String RequestMessageId_SearchBySerialNumber = 'A-A';
    public static String RequestMessageId_RequestCertificate   = 'BB';
    public static String RequestMessageId_RetrieveCertificate   = 'CC';
    
    public static final String PPSR_SERVICE_Endpoint = 'PPSR_Service_Endpoint';
    public static final String PPSR_SERVICE_Username= 'PPSR_Service_Username';
    public static final String PPSR_SERVICE_Password = 'PPSR_Service_Password';
    public static final String PPSR_SERVICE_SearchBySerial= 'PPSR_SoapAct_SearchBySerial';
    public static final String PPSR_SERVICE_RequestCertf = 'PPSR_SoapAct_RequestCertf';
    public static final String PPSR_SERVICE_RetrieveCertf= 'PPSR_SoapAct_RetrieveCertf';
    public static final String PPSR_SERVICE_PROXY_Endpoint = 'PPSR_Service_Proxy_Endpoint';
    
    public static final String PPSR_SERVICE_Email_Address= 'PPSR_Service_Email_Address';
    public static final String PPSR_SERVICE_Environment= 'PPSR_Service_Environment';

}