public class QuoteWrapper {
    public class Table {
        @AuraEnabled
        public String Profile;
        @AuraEnabled
        public String Tier;
        @AuraEnabled
        public Decimal Min_Equifax_Score;
        @AuraEnabled
        public String Overs;
        @AuraEnabled
        public String Rate0;
        @AuraEnabled
        public String Rate1;
        @AuraEnabled
        public String Rate2;
        @AuraEnabled
        public String Rate3;
        @AuraEnabled
        public String Rate4;
        @AuraEnabled
        public String Name;
        @AuraEnabled
        public String Rate;
        @AuraEnabled
        public String Type;
        @AuraEnabled
        public Decimal Min;
        @AuraEnabled
        public Decimal Max;
        @AuraEnabled
        public Decimal X6;
        @AuraEnabled
        public Decimal X9;
        @AuraEnabled
        public Decimal X12;
        @AuraEnabled
        public Decimal X18;
        @AuraEnabled
        public Decimal X24;
        @AuraEnabled
        public Decimal X36;
        @AuraEnabled
        public Decimal X48;
        @AuraEnabled
        public Decimal X60;
        @AuraEnabled
        public String Product;
        @AuraEnabled
        public String Year;
        @AuraEnabled
        public String R1;
        @AuraEnabled
        public String R2;
        @AuraEnabled
        public String R3;
    } 
    
    public class Picklist {
        @AuraEnabled
        public String label;
        @AuraEnabled
        public String value;
    }
}