public class QuoteWrapper {
    public class Table {
        @AuraEnabled
        public String Profile;
        @AuraEnabled
        public String Tier;
        @AuraEnabled
        public Decimal Min_Equifax_Score;
        @AuraEnabled
        public Decimal Overs;
        @AuraEnabled
        public Decimal Rate0;
        @AuraEnabled
        public Decimal Rate1;
        @AuraEnabled
        public Decimal Rate2;
        @AuraEnabled
        public Decimal Rate3;
        @AuraEnabled
        public Decimal Rate4;
        @AuraEnabled
        public String Name;
        @AuraEnabled
        public Decimal Rate;
        @AuraEnabled
        public String Type;
    } 
}