@isTest(SeeAllData=true)
public class TestYTDCalculator {

    public static testMethod void YTDCalculatorDTO(){
        YTDCalculatorDTO o = new YTDCalculatorDTO();
        
        o.ytdLender = 'l';
        o.startDate = 's';
        o.endDate = 's';
        o.ytdWeeks = 's';
        o.ytdIncome = 's';					
        o.baseIncome = 's';					
        o.ytdMonIncome = 's';
        o.netMonIncome = 's';
        o.monDifference = 's';
        o.baseTax = 's';
        o.baseMedi = 's';
        o.ytdComment1 = 's';
        o.startDateA2 = 's';
        o.endDateA2 = 's';
        o.ytdWeeksA2 = 's';
        o.ytdIncomeA2 = 's';
        o.baseIncomeA2 = 's';
        o.ytdMonIncomeA2 = 's';
        o.netMonIncomeA2 = 's';
        o.monDifferenceA2 = 's';
        o.discDiffA2 = 's';
        o.outAmountA2 = 's';
        o.ytdComment2 = 's';
        o.annualIncome = 's';
        o.ytdTax = 's';
        o.ytdMedi = 's';
        o.discDiff = 's';
        o.outAmount = 's';
        o.startDateOthA2 = 's';
        o.endDateOthA2 = 's';
        o.ytdWeeksOthA2 = 's';
        o.ytdIncomeOthA2 = 's';
        o.ytdMonIncomeOthA2 = 's';
        o.annualIncomeOthA2 = 's';
        o.startYtdDate = 's';
        o.ytdMacPayPeriodDays = 's';
        o.ytdMacMonthlyNetYtdSalary = 's';
        o.ytdMacAnnuallyNetYtdSalary = 's';
        o.ytdMacMonthlyPayPeriodNetSalary = 's';
        o.ytdMacAnnuallyPayPeriodNetSalary = 's';
        o.ytdMacComments = 's';
        o.startYtdDateA2 = 's';
        o.ytdMacStartDateA2 = 's';
        o.ytdMacEndDateA2 = 's';
        o.ytdMacNetYtdSalaryA2 = 's';
        o.ytdMacPayPeriodNetSalaryA2 = 's';
        o.ytdMacPayPeriodDaysA2 = 's';
        o.ytdMacMonthlyNetYtdSalaryA2 = 's';
        o.ytdMacAnnuallyNetYtdSalaryA2 = 's';
        o.ytdMacMonthlyPayPeriodNetSalaryA2 = 's';
        o.ytdMacAnnuallyPayPeriodNetSalaryA2 = 's';
        o.ytdMacCommentsA2 = 's';
        o.attachmentId = 's';
        o.fdLender = 's';
        o.fdNetProfit = 10000.00; 
        o.fdNetProfitDiscount = 10000.00;
        o.fdDepreciation = 10000.00;
        o.fdInterest = 10000.00;
        o.fdDirectorSalary = 10000.00;
        o.fullDocumentationTotal = 10000.00;
        o.fullDocTotalMonthly = 10000.00;
        o.sgtPaylipsFrecuency = 's';
        o.sgtPaylipsFrecuency1 = 's';
        o.sgtPaylipsFrecuency2 = 's';
        o.sgtPaylipsFrecuency3 = 's';
        o.sgtPaylipsAmount = 10000.00; 
        o.sgtPaylipsAmount1 = 10000.00; 
        o.sgtPaylipsAmount2 = 10000.00; 
        o.sgtPaylipsAmount3 = 10000.00;
        o.permanentMonthlyTotal = 10000.00; 
        o.casualMonthlyTotal1 = 10000.00; 
        o.casualMonthlyTotal2 = 10000.00; 
        o.casualMonthlyTotal3 = 10000.00; 
        o.casualTotalAverage = 10000.00; 
        o.sgtPaylipsFrecuencyA2 = 's';
        o.sgtPaylipsFrecuency1A2 = 's';
        o.sgtPaylipsFrecuency2A2 = 's';
        o.sgtPaylipsFrecuency3A2 = 's';
        o.sgtPaylipsAmountA2 = 10000.00;
        o.sgtPaylipsAmount1A2 = 10000.00;
        o.sgtPaylipsAmount2A2 = 10000.00;
        o.sgtPaylipsAmount3A2 = 10000.00;
        o.permanentMonthlyTotalA2 = 10000.00;
        o.casualMonthlyTotal1A2 = 10000.00;
        o.casualMonthlyTotal2A2 = 10000.00;
        o.casualMonthlyTotal3A2 = 10000.00;
        o.casualTotalAverageA2 = 10000.00;
        o.selfEmployedClass = 's';
        o.selfEmployedType = 's';
        o.latestPay1 = 10000.00;
        o.latestPay2 = 10000.00;
        o.latestPayMonthly1 = 10000.00;
        o.latestPayMonthly2 = 10000.00;
        o.latestPayFrequency1 = 's';
        o.latestPayFrequency2 = 's';
        o.servMonthlyRepayment = 10000.00;
        o.trusteesNumber = 's';
        o.fdNetProfit2 = 10000.00;
        o.fullDocumentationTotal2 = 10000.00;
        o.fullDocTotalMonthly2 = 10000.00;
        o.sales = 10000.00;
        o.YTDGrossLenderApplic1 = 's';
        o.GrossAnnualIncomeApplic1 = 10000.00;
        o.YTDGrossLenderApplic2 = 's';
        o.GrossAnnualIncomeApplic2 = 10000.00;
        o.selfEmployedClass2 = 's';
        o.selfEmployedType2 = 's';
        o.sales2 = 10000.00;
        o.fdNetProfit_2 = 10000.00;
        o.fdDepreciation2 = 10000.00;
        o.fdInterest2 = 10000.00;
        o.fdDirectorSalary2 = 10000.00;
        o.trusteesNumber2 = 's';
        o.fdNetProfit2_2 = 10000.00;
        o.fullDocumentationTotal_2 = 10000.00;
        o.fullDocumentationTotal2_2 = 10000.00;
        o.fullDocTotalMonthly_2 = 10000.00;
        o.fullDocTotalMonthly2_2 = 10000.00;
        o.fdNetProfitDiscount2 = 10000.00;
        o.getStGeorgeApplicant2();
        o.getIsEsandaApplicant2();
        o.getIsMacquarieApplicant2();
        o.getIsOthersApplicant2();
        o.getIsSelfEmployedApplicant2();
    }
    
    public static testMethod void YTDCalculatorExtension(){
        /*
        Test_DataGeneratorHelper.createApplication();
        Test_DataGeneratorHelper.createApplicationYTD();
        Test_DataGeneratorHelper.reloadOpportunity();
        ApexPages.StandardController ape = new ApexPages.StandardController(Test_DataGeneratorHelper.tstOpportunity);
        YTDCalculatorExtension myPageCon = new YTDCalculatorExtension(ape);
        myPageCon.ytdCalcLender = 'Esanda';
        myPageCon.ytdMonIncome = 50000;
        myPageCon.netMonIncome = 50000;
        myPageCon.monDifference = 50000;
        myPageCon.baseTax = 50000;
        myPageCon.baseMedi = 50000;
        myPageCon.startDate = Date.valueOf('2011-06-23');
        myPageCon.endDate = System.today();
        //myPageCon.ytdCalcWeeksBeteenDates();
        myPageCon.startDate = Date.valueOf('2013-06-23');
        myPageCon.endDate = Date.valueOf('2011-06-23');
        //myPageCon.ytdCalcWeeksBeteenDates();
        
        myPageCon.startDateA2 = Date.valueOf('2011-06-23');
        myPageCon.endDateA2 = System.today();
        //myPageCon.ytdCalcWeeksBeteenDatesA2();
        myPageCon.startDateA2 = Date.valueOf('2013-06-23');
        myPageCon.endDateA2 = Date.valueOf('2011-06-23');
        //myPageCon.ytdCalcWeeksBeteenDatesA2();
        
        //myPageCon.ytdCalcYtdNetMonthly();
        myPageCon.ytdIncome = 500;
        myPageCon.ytdWeeks = 4;
        myPageCon.netMonIncome = 2000;
        //myPageCon.ytdCalcYtdNetMonthly();
        
        myPageCon.ytdIncomeA2 = 0;
        myPageCon.ytdWeeksA2 = 0;
        myPageCon.netMonIncomeA2 = 0;
        //myPageCon.ytdCalcYtdNetMonthlyA2();
        myPageCon.ytdIncomeA2 = 500;
        myPageCon.ytdWeeksA2 = 4;
        myPageCon.netMonIncomeA2 = 2000;
        //myPageCon.ytdCalcYtdNetMonthlyA2();
        
        myPageCon.baseIncome = 2000;
        myPageCon.ytdCalcLender = 'Esanda';
        //myPageCon.ytdCalcBaseIncome();
        myPageCon.ytdCalcLender = 'Pepper';
        //myPageCon.ytdCalcBaseIncome();
        
        myPageCon.baseIncomeA2 = 2000;
        myPageCon.ytdCalcLender = 'Esanda';
        //myPageCon.ytdCalcBaseIncomeA2();
        myPageCon.ytdCalcLender = 'Pepper';
        //myPageCon.ytdCalcBaseIncomeA2();
        
        myPageCon.ytdMacPayPeriodNetSalary = 2000;
        myPageCon.ytdMacPayPeriodDays = 48;
        myPageCon.ytdMacStartDate = Date.valueOf('2011-06-23');
        myPageCon.ytdMacEndDate = System.today();
        //myPageCon.ytdMacDayssBeteenDates();
        myPageCon.ytdMacStartDate = Date.valueOf('2013-06-23');
        myPageCon.ytdMacEndDate = Date.valueOf('2011-06-23');
        //myPageCon.ytdMacDayssBeteenDates();
        
        myPageCon.ytdMacPayPeriodNetSalaryA2 = 2000;
        myPageCon.ytdMacPayPeriodDaysA2 = 48;
        myPageCon.ytdMacStartDateA2 = Date.valueOf('2011-06-23');
        myPageCon.ytdMacEndDateA2 = System.today();
        //myPageCon.ytdMacDayssBeteenDatesA2();
        myPageCon.ytdMacStartDateA2 = Date.valueOf('2013-06-23');
        myPageCon.ytdMacEndDateA2 = Date.valueOf('2011-06-23');
        //myPageCon.ytdMacDayssBeteenDatesA2();
        
        //myPageCon.ytdMacCalcPayPeriodSalary();
        myPageCon.startDate = Date.valueOf('2013-06-23');
        myPageCon.endDate = Date.valueOf('2019-06-23');
        myPageCon.ytdMonIncome = 10000;
        myPageCon.netMonIncome = 10000;
        myPageCon.startDateA2 = Date.valueOf('2013-06-23');
        myPageCon.endDateA2 = Date.valueOf('2019-06-23');
        myPageCon.ytdMonIncomeA2 = 10000;
        myPageCon.netMonIncomeA2 = 10000;
        myPageCon.ytdSavePdf();
        try { myPageCon.ytdSavePreApprovalPdf(); } catch(DmlException e) {}
        myPageCon.ytdCalcLender = 'Pepper';
        myPageCon.ytdSavePdf();
        try { myPageCon.ytdSavePreApprovalPdf(); } catch(DmlException e) {}
        myPageCon.ytdMacYtdStartDate = Date.valueOf('2013-06-23');
        myPageCon.ytdMacPayPeriodDays = 10000;
        myPageCon.ytdMacNetYtdSalary = 10000;
        myPageCon.ytdMacPayPeriodNetSalary = 10000;
        myPageCon.ytdMacMonthlyNetYtdSalary = 10000;
        myPageCon.ytdMacAnnuallyNetYtdSalary = 10000;
        myPageCon.ytdMacMonthlyPayPeriodNetSalary = 10000;
        myPageCon.ytdMacAnnuallyPayPeriodNetSalary = 10000;
        myPageCon.ytdMacStartDate = Date.valueOf('2013-06-23');
        myPageCon.ytdMacEndDate = Date.valueOf('2019-06-23');
        myPageCon.ytdMacYtdStartDateA2 = Date.valueOf('2013-06-23');
        myPageCon.ytdMacStartDateA2 = Date.valueOf('2013-06-23');
        myPageCon.ytdMacEndDateA2 = Date.valueOf('2019-06-23');
        myPageCon.ytdMacPayPeriodDaysA2 = 10000;
        myPageCon.ytdMacNetYtdSalaryA2 = 10000;
        myPageCon.ytdMacPayPeriodNetSalaryA2 = 10000;
        myPageCon.ytdMacMonthlyNetYtdSalaryA2 = 10000;
        myPageCon.ytdMacAnnuallyNetYtdSalaryA2 = 10000;
        myPageCon.ytdMacMonthlyPayPeriodNetSalaryA2 = 10000;
        myPageCon.ytdMacAnnuallyPayPeriodNetSalaryA2 = 10000;
        myPageCon.ytdCalcLender = 'Macquarie';
        myPageCon.ytdSavePdf();
        try { myPageCon.ytdSavePreApprovalPdf(); } catch(DmlException e) {}
        myPageCon.startDateOth = Date.valueOf('2013-06-23');
        myPageCon.endDateOth = Date.valueOf('2019-06-23');
        myPageCon.ytdIncomeOth = 10000;
        myPageCon.startDateOthA2 = Date.valueOf('2013-06-23');
        myPageCon.endDateOthA2 = Date.valueOf('2019-06-23');
        myPageCon.ytdIncomeOthA2 = 10000;
        myPageCon.ytdLenderApplic = 'Firstmac';
        myPageCon.ytdGrossAnnualIncomeApplic1 = 10000;
        myPageCon.ytdGrossAnnualIncomeApplic2 = 10000;
        myPageCon.ytdCalcLender = 'Others';
        myPageCon.ytdSavePdf();
        try { myPageCon.ytdSavePreApprovalPdf(); } catch(DmlException e) {}
        myPageCon.startDateOth = Date.valueOf('2013-06-23');
        myPageCon.endDateOth = Date.valueOf('2019-06-23');
        myPageCon.ytdIncomeOth = 10000;
        myPageCon.startDateOthA2 = Date.valueOf('2013-06-23');
        myPageCon.endDateOthA2 = Date.valueOf('2019-06-23');
        myPageCon.ytdIncomeOthA2 = 10000;
        myPageCon.ytdLenderApplic = 'Firstmac';
        myPageCon.ytdGrossAnnualIncomeApplic1 = 0;
        myPageCon.ytdGrossAnnualIncomeApplic2 = 0;
        myPageCon.ytdCalcLender = 'Others';
        myPageCon.ytdSavePdf();
        try { myPageCon.ytdSavePreApprovalPdf(); } catch(DmlException e) {}
        myPageCon.ytdCalcLender = 'LowDocumentation';
        myPageCon.ytdSavePdf();
        try { myPageCon.ytdSavePreApprovalPdf(); } catch(DmlException e) {}
        myPageCon.fdNetProfit = 10000;
        myPageCon.fdNetProfit_2 = 10000;
        myPageCon.ytdCalcLender = 'Self-Employed';
        myPageCon.ytdSavePdf();
        try { myPageCon.ytdSavePreApprovalPdf(); } catch(DmlException e) {}
        myPageCon.fdNetProfit = 10000;
        myPageCon.fdNetProfit_2 = 10000;
        myPageCon.fldSelfEmployedType = 'Trust';
        myPageCon.fldSelfEmployedType2 = 'Trust';
        myPageCon.ytdCalcLender = 'Self-Employed';
        myPageCon.ytdSavePdf();
        try { myPageCon.ytdSavePreApprovalPdf(); } catch(DmlException e) {}
        
        myPageCon.sgtPaylipsFrecuency = 'Weekly';
        myPageCon.sgtPaylipsFrecuency1 = 'Weekly';
        myPageCon.sgtPaylipsFrecuency2 = 'Weekly';
        myPageCon.sgtPaylipsFrecuency3 = 'Weekly';
        myPageCon.sgtPaylipsFrecuencyA2 = 'Weekly';
        myPageCon.sgtPaylipsFrecuency1A2 = 'Weekly';
        myPageCon.sgtPaylipsFrecuency2A2 = 'Weekly';
        myPageCon.sgtPaylipsFrecuency3A2 = 'Weekly';
        myPageCon.sgtPaylipsAmount = 2;
        myPageCon.sgtPaylipsAmount1 = 2;
        myPageCon.sgtPaylipsAmount2 = 2;
        myPageCon.sgtPaylipsAmount3 = 2;
        myPageCon.sgtPaylipsAmountA2 = 2;
        myPageCon.sgtPaylipsAmount1A2 = 2;
        myPageCon.sgtPaylipsAmount2A2 = 2;
        myPageCon.sgtPaylipsAmount3A2 = 2;
        myPageCon.fdNetProfit2 = 2;
        
        myPageCon.getPermanentMonthlyTotal();
        myPageCon.getCasualMonthlyTotal1();
        myPageCon.getCasualMonthlyTotal2();
        myPageCon.getCasualMonthlyTotal3();
        myPageCon.getCasualTotalAverage();
        myPageCon.getPermanentMonthlyTotalA2();
        myPageCon.getCasualMonthlyTotal1A2();
        myPageCon.getCasualMonthlyTotal2A2();
        myPageCon.getCasualMonthlyTotal3A2();
        //myPageCon.getFullDocumentationTotal();
        //myPageCon.getFullDocumentationMonthlyTotal();
        myPageCon.getCasualTotalAverageA2();
        
        //myPageCon.getFullDocumentationTotal2();
        //myPageCon.getFullDocumentationMonthlyTotal2();
        
        //myPageCon.ytdMacCalcPayPeriodSalaryA2();
        
        //myPageCon.ytdCalculateA2();
        myPageCon.ytdIncomeOthA2 = 2000;
        myPageCon.ytdWeeksOthA2 = 0;
        myPageCon.startDateOthA2 = Date.valueOf('2011-06-23');
        myPageCon.endDateOthA2 = System.today();
        //myPageCon.ytdCalculateA2();
        myPageCon.startDateOthA2 = Date.valueOf('2013-06-23');
        myPageCon.endDateOthA2 = Date.valueOf('2011-06-23');
        //myPageCon.ytdCalculateA2();
        
        myPageCon.latestPay1 = 10000.00;
        myPageCon.latestPayFrequency1 = 'Weekly';
        myPageCon.ytdCalcNetLastestPay1();
        myPageCon.latestPay2 = 10000.00;
        myPageCon.latestPayFrequency2 = 'Weekly';
        myPageCon.ytdCalcNetLastestPay2();
        
        //myPageCon.getFullDocumentationTotal_2();
        //myPageCon.getFullDocumentationTotal2_2();
        //myPageCon.getFullDocumentationMonthlyTotal_2();
        //myPageCon.getFullDocumentationMonthlyTotal2_2();
        
        myPageCon.ytdCalcLender = 'Esanda';
        myPageCon.clearYTDEsandaOtherFields();
        myPageCon.ytdCalcLender = 'Macquarie';
        myPageCon.clearYTDEsandaOtherFields();
        myPageCon.ytdCalcLender = 'Others';
        myPageCon.clearYTDEsandaOtherFields();
        
        myPageCon.startDateOth = Date.valueOf('2013-06-23');
        myPageCon.endDateOth = Date.valueOf('2011-06-23');
        //myPageCon.ytdCalculate();
        
        myPageCon.startDateOth = Date.valueOf('2011-06-23');
        myPageCon.endDateOth = Date.valueOf('2013-06-23');
        myPageCon.ytdIncomeOth = 10000.00;
        //myPageCon.ytdCalculate();
        
        myPageCon.ytdMacYtdStartDate = Date.valueOf('2011-06-23');
        myPageCon.ytdMacEndDate = Date.valueOf('2013-06-23');
        myPageCon.ytdMacNetYtdSalary = 10000.00;
        //myPageCon.ytdMacNetYTDSalary();
        myPageCon.ytdMacNetYtdSalaryA2 = 10000.00;
        myPageCon.ytdMacYtdStartDateA2 = Date.valueOf('2011-06-23');
        myPageCon.ytdMacEndDateA2 = Date.valueOf('2013-06-23');
        //myPageCon.ytdMacNetYTDSalaryA2();
        
        Test_DataGeneratorHelper.createApplicationYTD();
        Test_DataGeneratorHelper.reloadOpportunity();
        Test_DataGeneratorHelper.tstOpportunity.ApplicationYTD__r.Type__c = 'Macquarie';
        ApexPages.StandardController ape2 = new ApexPages.StandardController(Test_DataGeneratorHelper.tstOpportunity);
        YTDCalculatorExtension myPageCon2 = new YTDCalculatorExtension(ape2);
        
        Test_DataGeneratorHelper.createApplicationYTD();
        Test_DataGeneratorHelper.reloadOpportunity();
        Test_DataGeneratorHelper.tstOpportunity.ApplicationYTD__r.Type__c = 'Others';
        ApexPages.StandardController ape3 = new ApexPages.StandardController(Test_DataGeneratorHelper.tstOpportunity);
        YTDCalculatorExtension myPageCon3 = new YTDCalculatorExtension(ape3);
        
        Test_DataGeneratorHelper.createApplicationYTD();
        Test_DataGeneratorHelper.reloadOpportunity();
        Test_DataGeneratorHelper.tstOpportunity.ApplicationYTD__r.Type__c = 'Self-Employed';
        ApexPages.StandardController ape4 = new ApexPages.StandardController(Test_DataGeneratorHelper.tstOpportunity);
        YTDCalculatorExtension myPageCon4 = new YTDCalculatorExtension(ape4);
        
        Test_DataGeneratorHelper.createApplication();
        Test_DataGeneratorHelper.createApplicationYTD();
        Test_DataGeneratorHelper.reloadOpportunity();
        Test_DataGeneratorHelper.tstOpportunity.Application__r.No_of_People__c = 1;
        ApexPages.StandardController ape5 = new ApexPages.StandardController(Test_DataGeneratorHelper.tstOpportunity);
        YTDCalculatorExtension myPageCon5 = new YTDCalculatorExtension(ape5);
        
        myPageCon5.startDate = Date.valueOf('2013-06-23');
        myPageCon5.endDate = Date.valueOf('2019-06-23');
        myPageCon5.startDateA2 = Date.valueOf('2013-06-23');
        myPageCon5.endDateA2 = Date.valueOf('2019-06-23');
        myPageCon5.ytdSavePdf();
        try { myPageCon5.ytdSavePreApprovalPdf(); } catch(DmlException e) {}
        myPageCon5.ytdCalcLender = 'Pepper';
        myPageCon5.ytdSavePdf();
        try { myPageCon5.ytdSavePreApprovalPdf(); } catch(DmlException e) {}
        myPageCon5.ytdMacYtdStartDate = Date.valueOf('2013-06-23');
        myPageCon5.ytdMacPayPeriodDays = 10000;
        myPageCon5.ytdMacNetYtdSalary = 10000;
        myPageCon5.ytdMacPayPeriodNetSalary = 10000;
        myPageCon5.ytdMacMonthlyNetYtdSalary = 10000;
        myPageCon5.ytdMacAnnuallyNetYtdSalary = 10000;
        myPageCon5.ytdMacMonthlyPayPeriodNetSalary = 10000;
        myPageCon5.ytdMacAnnuallyPayPeriodNetSalary = 10000;
        myPageCon5.ytdMacStartDate = Date.valueOf('2013-06-23');
        myPageCon5.ytdMacEndDate = Date.valueOf('2019-06-23');
        myPageCon5.ytdMacYtdStartDateA2 = Date.valueOf('2013-06-23');
        myPageCon5.ytdMacStartDateA2 = Date.valueOf('2013-06-23');
        myPageCon5.ytdMacEndDateA2 = Date.valueOf('2019-06-23');
        myPageCon5.ytdMacPayPeriodDaysA2 = 10000;
        myPageCon5.ytdMacNetYtdSalaryA2 = 10000;
        myPageCon5.ytdMacPayPeriodNetSalaryA2 = 10000;
        myPageCon5.ytdMacMonthlyNetYtdSalaryA2 = 10000;
        myPageCon5.ytdMacAnnuallyNetYtdSalaryA2 = 10000;
        myPageCon5.ytdMacMonthlyPayPeriodNetSalaryA2 = 10000;
        myPageCon5.ytdMacAnnuallyPayPeriodNetSalaryA2 = 10000;
        myPageCon5.ytdCalcLender = 'Macquarie';
        myPageCon5.ytdSavePdf();
        try { myPageCon5.ytdSavePreApprovalPdf(); } catch(DmlException e) {}
        myPageCon5.startDateOth = Date.valueOf('2013-06-23');
        myPageCon5.endDateOth = Date.valueOf('2019-06-23');
        myPageCon5.startDateOthA2 = Date.valueOf('2013-06-23');
        myPageCon5.endDateOthA2 = Date.valueOf('2019-06-23');
        myPageCon5.ytdLenderApplic = 'Firstmac';
        myPageCon5.ytdCalcLender = 'Others';
        myPageCon5.ytdSavePdf();
        try { myPageCon5.ytdSavePreApprovalPdf(); } catch(DmlException e) {}
        myPageCon5.startDateOth = Date.valueOf('2013-06-23');
        myPageCon5.endDateOth = Date.valueOf('2019-06-23');
        myPageCon5.ytdIncomeOth = 10000;
        myPageCon5.startDateOthA2 = Date.valueOf('2013-06-23');
        myPageCon5.endDateOthA2 = Date.valueOf('2019-06-23');
        myPageCon5.ytdIncomeOthA2 = 10000;
        myPageCon5.ytdLenderApplic = 'Firstmac';
        myPageCon5.ytdGrossAnnualIncomeApplic1 = 0;
        myPageCon5.ytdGrossAnnualIncomeApplic2 = 0;
        myPageCon5.ytdCalcLender = 'Others';
        myPageCon5.ytdSavePdf();
        try { myPageCon5.ytdSavePreApprovalPdf(); } catch(DmlException e) {}
        myPageCon5.fdNetProfit = 10000;
        myPageCon5.fdNetProfit_2 = 10000;
        myPageCon5.ytdCalcLender = 'Self-Employed';
        myPageCon5.ytdSavePdf();
        try { myPageCon5.ytdSavePreApprovalPdf(); } catch(DmlException e) {}
        myPageCon5.fdNetProfit = 10000;
        myPageCon5.fdNetProfit_2 = 10000;
        myPageCon5.fldSelfEmployedType = 'Trust';
        myPageCon5.fldSelfEmployedType2 = 'Trust';
        myPageCon5.ytdCalcLender = 'Self-Employed';
        myPageCon5.ytdSavePdf();
        try { myPageCon5.ytdSavePreApprovalPdf(); } catch(DmlException e) {}
        */
        Test_DataGeneratorHelper.createApplication();
        Test_DataGeneratorHelper.createApplicationYTD();
        Test_DataGeneratorHelper.reloadOpportunity();
        Test_DataGeneratorHelper.tstOpportunity.ApplicationYTD__r.Type__c = 'Macquarie';
        ApexPages.StandardController ape2 = new ApexPages.StandardController(Test_DataGeneratorHelper.tstOpportunity);
        YTDCalculatorExtension myPageCon2 = new YTDCalculatorExtension(ape2);
        
        Test_DataGeneratorHelper.createApplicationYTD();
        Test_DataGeneratorHelper.reloadOpportunity();
        Test_DataGeneratorHelper.tstOpportunity.ApplicationYTD__r.Type__c = 'Others';
        ApexPages.StandardController ape3 = new ApexPages.StandardController(Test_DataGeneratorHelper.tstOpportunity);
        YTDCalculatorExtension myPageCon3 = new YTDCalculatorExtension(ape3);
        myPageCon3.data();
        myPageCon3.ytdCalcLender = 'Others';
        myPageCon3.clearYTDEsandaOtherFields();
        
        Test_DataGeneratorHelper.createApplicationYTD();
        Test_DataGeneratorHelper.reloadOpportunity();
        Test_DataGeneratorHelper.tstOpportunity.ApplicationYTD__r.Type__c = 'Self-Employed';
        ApexPages.StandardController ape4 = new ApexPages.StandardController(Test_DataGeneratorHelper.tstOpportunity);
        YTDCalculatorExtension myPageCon4 = new YTDCalculatorExtension(ape4);
        
        Test_DataGeneratorHelper.createApplication();
        Test_DataGeneratorHelper.reloadOpportunity();
        createApplicationEmployment();
        ApexPages.StandardController ape5 = new ApexPages.StandardController(Test_DataGeneratorHelper.tstOpportunity);
        YTDCalculatorExtension myPageCon5 = new YTDCalculatorExtension(ape5);
        
        Map<String, Boolean> data = new Map<String, Boolean>();
        data.put(YTDCalculatorExtension.APPTYPE_1_2NDJOB, true);
        data.put(YTDCalculatorExtension.APPTYPE_2_2NDJOB, true);
        YTDCalculatorExtension.removeIncomes(Test_DataGeneratorHelper.tstOpportunity.Id , Test_DataGeneratorHelper.tstOpportunity.Application__r.No_of_People__c, data);
        Test_DataGeneratorHelper.tstOpportunity.Application__r.No_of_People__c = 1;
        YTDCalculatorExtension.removeIncomes(Test_DataGeneratorHelper.tstOpportunity.Id , Test_DataGeneratorHelper.tstOpportunity.Application__r.No_of_People__c, data);
        data.clear();
        data.put(YTDCalculatorExtension.APPTYPE_1_2NDJOB, false);
        data.put(YTDCalculatorExtension.APPTYPE_2_2NDJOB, false);
        YTDCalculatorExtension.removeIncomes(Test_DataGeneratorHelper.tstOpportunity.Id , Test_DataGeneratorHelper.tstOpportunity.Application__r.No_of_People__c, data);
        
        myPageCon5.startDateOth = Date.valueOf('2013-06-23');
        myPageCon5.endDateOth = Date.valueOf('2011-06-23');
        myPageCon5.ytdCalculate();
        myPageCon5.startDateOth = Date.valueOf('2011-06-23');
        myPageCon5.endDateOth = Date.valueOf('2013-06-23');
        myPageCon5.ytdIncomeOth = 10000.00;
        myPageCon5.ytdCalculate();
        
        Test_DataGeneratorHelper.createApplication();
        createIncomeYTD('Esanda');
        Test_DataGeneratorHelper.reloadOpportunity();
        createApplicationEmployment();
        ApexPages.StandardController ape6 = new ApexPages.StandardController(Test_DataGeneratorHelper.tstOpportunity);
        YTDCalculatorExtension myPageCon6 = new YTDCalculatorExtension(ape6);
        myPageCon6.ytdSavePdf();
        myPageCon6.ytdSavePreApprovalPdf();
        
        myPageCon6.ytdCalcLender = 'Pepper';
        myPageCon6.clearYTDEsandaOtherFields();
        myPageCon6.ytdCalcLender = 'Others';
        myPageCon6.clearYTDEsandaOtherFields();
        myPageCon6.ytdCalcLender = 'Macquarie';
        myPageCon6.clearYTDEsandaOtherFields();
        myPageCon6.ytdCalcLender = 'Self-Employed';
        myPageCon6.clearYTDEsandaOtherFields();
                  
        Test_DataGeneratorHelper.createApplication();
        createIncomeYTD('Pepper');
        Test_DataGeneratorHelper.reloadOpportunity();
        createApplicationEmployment();
        ApexPages.StandardController ape7 = new ApexPages.StandardController(Test_DataGeneratorHelper.tstOpportunity);
        YTDCalculatorExtension myPageCon7 = new YTDCalculatorExtension(ape7);
        myPageCon7.ytdCalcLender = 'Pepper';
        myPageCon7.clearYTDEsandaOtherFields();
        
        myPageCon7.ytdSavePdf();
        myPageCon7.ytdSavePreApprovalPdf();
        
        Test_DataGeneratorHelper.createApplication();
        createIncomeYTD('Others');
        Test_DataGeneratorHelper.reloadOpportunity();
        createApplicationEmployment();
        ApexPages.StandardController ape8 = new ApexPages.StandardController(Test_DataGeneratorHelper.tstOpportunity);
        YTDCalculatorExtension myPageCon8 = new YTDCalculatorExtension(ape8);
        myPageCon8.ytdCalcLender = 'Others';
        myPageCon8.clearYTDEsandaOtherFields();
        
        myPageCon8.ytdSavePdf();
        myPageCon8.ytdSavePreApprovalPdf();
        
        Test_DataGeneratorHelper.createApplication();
        createIncomeYTD('Macquarie');
        Test_DataGeneratorHelper.reloadOpportunity();
        createApplicationEmployment();
        ApexPages.StandardController ape9 = new ApexPages.StandardController(Test_DataGeneratorHelper.tstOpportunity);
        YTDCalculatorExtension myPageCon9 = new YTDCalculatorExtension(ape9);
        myPageCon9.ytdCalcLender = 'Macquarie';
        myPageCon9.clearYTDEsandaOtherFields();
        
        myPageCon9.ytdSavePdf();
        myPageCon9.ytdSavePreApprovalPdf();
               
        Test_DataGeneratorHelper.createApplication();
        createIncomeYTD('Self-Employed');
        Test_DataGeneratorHelper.reloadOpportunity();
        createApplicationEmployment();
        ApexPages.StandardController ape10 = new ApexPages.StandardController(Test_DataGeneratorHelper.tstOpportunity);
        YTDCalculatorExtension myPageCon10 = new YTDCalculatorExtension(ape10);
        myPageCon10.ytdCalcLender = 'Self-Employed';
        myPageCon10.clearYTDEsandaOtherFields();
                
        myPageCon10.ytdSavePdf();
        myPageCon10.ytdSavePreApprovalPdf();
        myPageCon10.calculateWeeksApp1();
        myPageCon10.calculateWeeksApp2();
        myPageCon10.calculateWeeksApp12ndJob();
        myPageCon10.calculateWeeksApp22ndJob();
        myPageCon10.macNetYTDSalaryApp1();
        myPageCon10.macNetYTDSalaryApp12ndJob();
        myPageCon10.macNetYTDSalaryApp2();
        myPageCon10.macNetYTDSalaryApp22ndJob();
        myPageCon10.macCalcPayPeriodSalaryApp1();
        myPageCon10.macCalcPayPeriodSalaryApp12ndJob();
        myPageCon10.macCalcPayPeriodSalaryApp2();
        myPageCon10.macCalcPayPeriodSalaryApp22ndJob();
        myPageCon10.getFullDocumentationTotalApp1();
        myPageCon10.getFullDocumentationMonthlyTotalApp1();
        myPageCon10.getFullDocumentationTotal2App1();
        myPageCon10.getFullDocumentationTotalApp2();
        myPageCon10.getFullDocumentationTotal2App2();
        myPageCon10.getFullDocumentationTotalApp12ndJob();
        myPageCon10.getFullDocumentationTotal2App12ndJob();
        myPageCon10.getFullDocumentationTotalApp22ndJob();
        myPageCon10.getFullDocumentationTotal2App22ndJob();
        myPageCon10.fullDocumentationTotalApp1();
        myPageCon10.fullDocumentationTotalApp2();
        myPageCon10.fullDocumentationTotalApp12ndJob();
        myPageCon10.fullDocumentationTotalApp22ndJob();
        
        
        /*
        Test_DataGeneratorHelper.createApplicationYTD();
        Test_DataGeneratorHelper.reloadOpportunity();
        Test_DataGeneratorHelper.tstOpportunity.ApplicationYTD__r.Type__c = 'Others';
        ApexPages.StandardController ape3 = new ApexPages.StandardController(Test_DataGeneratorHelper.tstOpportunity);
        YTDCalculatorExtension myPageCon3 = new YTDCalculatorExtension(ape3);
        
        Test_DataGeneratorHelper.createApplicationYTD();
        Test_DataGeneratorHelper.reloadOpportunity();
        Test_DataGeneratorHelper.tstOpportunity.ApplicationYTD__r.Type__c = 'Self-Employed';
        ApexPages.StandardController ape4 = new ApexPages.StandardController(Test_DataGeneratorHelper.tstOpportunity);
        YTDCalculatorExtension myPageCon4 = new YTDCalculatorExtension(ape4);
        */
        Test_DataGeneratorHelper.createApplicationYTD();
        Test_DataGeneratorHelper.reloadOpportunity();
        ApexPages.StandardController ape = new ApexPages.StandardController(Test_DataGeneratorHelper.tstOpportunity);
        YTDCalculatorExtension myPageCon = new YTDCalculatorExtension(ape);
        
        myPageCon.sgtPaylipsFrecuency = 'Weekly';
        myPageCon.sgtPaylipsFrecuency1 = 'Weekly';
        myPageCon.sgtPaylipsFrecuency2 = 'Weekly';
        myPageCon.sgtPaylipsFrecuency3 = 'Weekly';
        myPageCon.sgtPaylipsFrecuencyA2 = 'Weekly';
        myPageCon.sgtPaylipsFrecuency1A2 = 'Weekly';
        myPageCon.sgtPaylipsFrecuency2A2 = 'Weekly';
        myPageCon.sgtPaylipsFrecuency3A2 = 'Weekly';
        myPageCon.sgtPaylipsAmount = 2;
        myPageCon.sgtPaylipsAmount1 = 2;
        myPageCon.sgtPaylipsAmount2 = 2;
        myPageCon.sgtPaylipsAmount3 = 2;
        myPageCon.sgtPaylipsAmountA2 = 2;
        myPageCon.sgtPaylipsAmount1A2 = 2;
        myPageCon.sgtPaylipsAmount2A2 = 2;
        myPageCon.sgtPaylipsAmount3A2 = 2;
        
        myPageCon.getPermanentMonthlyTotal();
        myPageCon.getCasualMonthlyTotal1();
        myPageCon.getCasualMonthlyTotal2();
        myPageCon.getCasualMonthlyTotal3();
        myPageCon.getCasualTotalAverage();
        myPageCon.getPermanentMonthlyTotalA2();
        myPageCon.getCasualMonthlyTotal1A2();
        myPageCon.getCasualMonthlyTotal2A2();
        myPageCon.getCasualMonthlyTotal3A2();
        myPageCon.getCasualTotalAverageA2();
        
        
        /*
        myPageCon6.getApp12ndJob();
        myPageCon6.getApp22ndJob();
        myPageCon6.calculateWeeksApp1();
        myPageCon6.calculateWeeksApp2();
        myPageCon6.calculateWeeksApp12ndJob();
        myPageCon6.calculateWeeksApp22ndJob();
        myPageCon6.calcWeeksBeteenDatesApp12ndJob();
        myPageCon6.calcWeeksBeteenDatesApp22ndJob();
        myPageCon6.macDayssBeteenDatesApp12ndJob();
        myPageCon6.macDayssBeteenDatesApp22ndJob();
        myPageCon6.macNetYTDSalaryApp1();
        myPageCon6.macNetYTDSalaryApp12ndJob();
        myPageCon6.macNetYTDSalaryApp2();
        myPageCon6.macNetYTDSalaryApp22ndJob();
        myPageCon6.macCalcPayPeriodSalaryApp1();
        myPageCon6.macCalcPayPeriodSalaryApp12ndJob();
        myPageCon6.macCalcPayPeriodSalaryApp2();
        myPageCon6.macCalcPayPeriodSalaryApp22ndJob();
        myPageCon6.getFullDocumentationTotalApp1();
        myPageCon6.getFullDocumentationMonthlyTotalApp1();
        myPageCon6.getFullDocumentationTotal2App1();
        myPageCon6.getFullDocumentationTotalApp2();
        myPageCon6.getFullDocumentationTotal2App2();
        myPageCon6.getFullDocumentationTotalApp12ndJob();
        myPageCon6.getFullDocumentationTotal2App12ndJob();
        myPageCon6.getFullDocumentationTotalApp22ndJob();
        myPageCon6.getFullDocumentationTotal2App22ndJob();
        myPageCon6.ytdCalcNetLastestPay12ndJob();
        myPageCon6.ytdCalcNetLastestPay22ndJob();
        myPageCon6.fullDocumentationTotalApp1();
        myPageCon6.fullDocumentationTotalApp2();
        myPageCon6.fullDocumentationTotalApp12ndJob();
        myPageCon6.fullDocumentationTotalApp22ndJob();
        myPageCon6.ytdSavePdf();
        myPageCon6.ytdSavePreApprovalPdf();
        myPageCon6.calcWeeksBeteenDatesApp2();
        myPageCon6.macDayssBeteenDatesApp1();
        myPageCon6.macDayssBeteenDatesApp2();
        myPageCon6.ytdCalcNetLastestPay1();
        myPageCon6.ytdCalcNetLastestPay2();
        */
        /*
        Test_DataGeneratorHelper.createApplication();
        Test_DataGeneratorHelper.createIncomeYTD('Macquarie');
        Test_DataGeneratorHelper.reloadOpportunity();
        Test_DataGeneratorHelper.createApplicationEmployment();
        ApexPages.StandardController ape7 = new ApexPages.StandardController(Test_DataGeneratorHelper.tstOpportunity);
        YTDCalculatorExtension myPageCon7 = new YTDCalculatorExtension(ape7);
        
        myPageCon7.getApp12ndJob();
        myPageCon7.getApp22ndJob();
        myPageCon7.calculateWeeksApp1();
        myPageCon7.calculateWeeksApp2();
        myPageCon7.calculateWeeksApp12ndJob();
        myPageCon7.calculateWeeksApp22ndJob();
        myPageCon7.calcWeeksBeteenDatesApp12ndJob();
        myPageCon7.calcWeeksBeteenDatesApp22ndJob();
        myPageCon7.macDayssBeteenDatesApp12ndJob();
        myPageCon7.macDayssBeteenDatesApp22ndJob();
        myPageCon7.macNetYTDSalaryApp1();
        myPageCon7.macNetYTDSalaryApp12ndJob();
        myPageCon7.macNetYTDSalaryApp2();
        myPageCon7.macNetYTDSalaryApp22ndJob();
        myPageCon7.macCalcPayPeriodSalaryApp1();
        myPageCon7.macCalcPayPeriodSalaryApp12ndJob();
        myPageCon7.macCalcPayPeriodSalaryApp2();
        myPageCon7.macCalcPayPeriodSalaryApp22ndJob();
        myPageCon7.getFullDocumentationTotalApp1();
        myPageCon7.getFullDocumentationMonthlyTotalApp1();
        myPageCon7.getFullDocumentationTotal2App1();
        myPageCon7.getFullDocumentationTotalApp2();
        myPageCon7.getFullDocumentationTotal2App2();
        myPageCon7.getFullDocumentationTotalApp12ndJob();
        myPageCon7.getFullDocumentationTotal2App12ndJob();
        myPageCon7.getFullDocumentationTotalApp22ndJob();
        myPageCon7.getFullDocumentationTotal2App22ndJob();
        myPageCon7.ytdCalcNetLastestPay12ndJob();
        myPageCon7.ytdCalcNetLastestPay22ndJob();
        myPageCon7.fullDocumentationTotalApp1();
        myPageCon7.fullDocumentationTotalApp2();
        myPageCon7.fullDocumentationTotalApp12ndJob();
        myPageCon7.fullDocumentationTotalApp22ndJob();
        myPageCon7.ytdSavePdf();
        myPageCon7.ytdSavePreApprovalPdf();
        myPageCon7.calcWeeksBeteenDatesApp2();
        myPageCon7.macDayssBeteenDatesApp1();
        myPageCon7.macDayssBeteenDatesApp2();
        myPageCon7.ytdCalcNetLastestPay1();
        myPageCon7.ytdCalcNetLastestPay2();
*/
 
        
    }
    
    public static void createIncomeYTD(String type) {
        YTD_Income__c o = new YTD_Income__c();
        o.Annualised_Income__c = 10000.00;
        o.Applicant_Type__c = YTDCalculatorExtension.APPTYPE_1;
        o.Comment__c = 'c';
        o.Depreciation__c = 10000.00;
        o.Difference__c = 10000.00;
        o.Director_Salary__c = 10000.00;
        o.Discounted__c = 10000.00;
        o.Employment_Start_Date__c = Date.valueOf('2020-02-25');
        o.End_Date__c = Date.valueOf('2020-02-26');
        o.Gross_Annual_Income__c = 10000.00;
        o.Gross_Net_Income__c = 10000.00;
        o.Gross_YTD_Income__c = 10000.00;
        o.Interest__c = 10000.00;
        o.Last_Income_Frequency__c = 'Monthly';
        o.Monthly_Amount__c = 10000.00;
        o.Net_Annual_Income__c = 10000.00;
        o.Net_Income__c = 10000.00;
        o.Net_Last_Income__c = 10000.00;
        o.Net_Monthly_Income_2__c = 10000.00;
        o.Net_Monthly_Income__c = 10000.00;
        o.Net_Profit_2__c = 10000.00;
        o.Net_Profit__c = 10000.00;
        o.Net_Profit_Calc_2__c = 10000.00;
        o.Net_Profit_Calc__c = 10000.00;
        o.Net_Profit_Calc_After_Tax__c = 10000.00;
        o.Net_YTD_Salary_Annually__c = 10000.00;
        o.Net_YTD_Salary_Monthly__c = 10000.00;
        o.Opportunity__c = Test_DataGeneratorHelper.tstOpportunity.Id;
        o.Pay_Period_Annually__c = 10000.00;
        o.Pay_Period_Monthly__c = 10000.00;
        o.Sales__c = 10000.00;
        o.Self_Employed_Class__c = 'Full-Doc';
        o.Self_Employed_Type__c = 'Company Pty Ltd';
        o.Start_Date__c = Date.valueOf('2020-02-25');
        o.Trustees_Number__c = '2';
        o.Type__c = type;
        
        insert o;
        
        o = new YTD_Income__c();
        o.Annualised_Income__c = 10000.00;
        o.Applicant_Type__c = YTDCalculatorExtension.APPTYPE_1_2NDJOB;
        o.Comment__c = 'c';
        o.Depreciation__c = 10000.00;
        o.Difference__c = 10000.00;
        o.Director_Salary__c = 10000.00;
        o.Discounted__c = 10000.00;
        o.Employment_Start_Date__c = Date.valueOf('2020-02-25');
        o.End_Date__c = Date.valueOf('2020-02-26');
        o.Gross_Annual_Income__c = 10000.00;
        o.Gross_Net_Income__c = 10000.00;
        o.Gross_YTD_Income__c = 10000.00;
        o.Interest__c = 10000.00;
        o.Last_Income_Frequency__c = 'Monthly';
        o.Monthly_Amount__c = 10000.00;
        o.Net_Annual_Income__c = 10000.00;
        o.Net_Income__c = 10000.00;
        o.Net_Last_Income__c = 10000.00;
        o.Net_Monthly_Income_2__c = 10000.00;
        o.Net_Monthly_Income__c = 10000.00;
        o.Net_Profit_2__c = 10000.00;
        o.Net_Profit__c = 10000.00;
        o.Net_Profit_Calc_2__c = 10000.00;
        o.Net_Profit_Calc__c = 10000.00;
        o.Net_Profit_Calc_After_Tax__c = 10000.00;
        o.Net_YTD_Salary_Annually__c = 10000.00;
        o.Net_YTD_Salary_Monthly__c = 10000.00;
        o.Opportunity__c = Test_DataGeneratorHelper.tstOpportunity.Id;
        o.Pay_Period_Annually__c = 10000.00;
        o.Pay_Period_Monthly__c = 10000.00;
        o.Sales__c = 10000.00;
        o.Self_Employed_Class__c = 'Full-Doc';
        o.Self_Employed_Type__c = 'Sole Trader';
        o.Start_Date__c = Date.valueOf('2020-02-25');
        o.Trustees_Number__c = '2';
        o.Type__c = type;
        
        insert o;
                
        o = new YTD_Income__c();
        o.Annualised_Income__c = 10000.00;
        o.Applicant_Type__c = YTDCalculatorExtension.APPTYPE_2;
        o.Comment__c = 'c';
        o.Depreciation__c = 10000.00;
        o.Difference__c = 10000.00;
        o.Director_Salary__c = 10000.00;
        o.Discounted__c = 10000.00;
        o.Employment_Start_Date__c = Date.valueOf('2020-02-25');
        o.End_Date__c = Date.valueOf('2020-02-26');
        o.Gross_Annual_Income__c = 10000.00;
        o.Gross_Net_Income__c = 10000.00;
        o.Gross_YTD_Income__c = 10000.00;
        o.Interest__c = 10000.00;
        o.Last_Income_Frequency__c = 'Monthly';
        o.Monthly_Amount__c = 10000.00;
        o.Net_Annual_Income__c = 10000.00;
        o.Net_Income__c = 10000.00;
        o.Net_Last_Income__c = 10000.00;
        o.Net_Monthly_Income_2__c = 10000.00;
        o.Net_Monthly_Income__c = 10000.00;
        o.Net_Profit_2__c = 10000.00;
        o.Net_Profit__c = 10000.00;
        o.Net_Profit_Calc_2__c = 10000.00;
        o.Net_Profit_Calc__c = 10000.00;
        o.Net_Profit_Calc_After_Tax__c = 10000.00;
        o.Net_YTD_Salary_Annually__c = 10000.00;
        o.Net_YTD_Salary_Monthly__c = 10000.00;
        o.Opportunity__c = Test_DataGeneratorHelper.tstOpportunity.Id;
        o.Pay_Period_Annually__c = 10000.00;
        o.Pay_Period_Monthly__c = 10000.00;
        o.Sales__c = 10000.00;
        o.Self_Employed_Class__c = 'Full-Doc';
        o.Self_Employed_Type__c = 'Trust';
        o.Start_Date__c = Date.valueOf('2020-02-25');
        o.Trustees_Number__c = '2';
        o.Type__c = type;
        
        insert o;
        
        o = new YTD_Income__c();
        o.Annualised_Income__c = 10000.00;
        o.Applicant_Type__c = YTDCalculatorExtension.APPTYPE_2_2NDJOB;
        o.Comment__c = 'c';
        o.Depreciation__c = 10000.00;
        o.Difference__c = 10000.00;
        o.Director_Salary__c = 10000.00;
        o.Discounted__c = 10000.00;
        o.Employment_Start_Date__c = Date.valueOf('2020-02-25');
        o.End_Date__c = Date.valueOf('2020-02-26');
        o.Gross_Annual_Income__c = 10000.00;
        o.Gross_Net_Income__c = 10000.00;
        o.Gross_YTD_Income__c = 10000.00;
        o.Interest__c = 10000.00;
        o.Last_Income_Frequency__c = 'Monthly';
        o.Monthly_Amount__c = 10000.00;
        o.Net_Annual_Income__c = 10000.00;
        o.Net_Income__c = 10000.00;
        o.Net_Last_Income__c = 10000.00;
        o.Net_Monthly_Income_2__c = 10000.00;
        o.Net_Monthly_Income__c = 10000.00;
        o.Net_Profit_2__c = 10000.00;
        o.Net_Profit__c = 10000.00;
        o.Net_Profit_Calc_2__c = 10000.00;
        o.Net_Profit_Calc__c = 10000.00;
        o.Net_Profit_Calc_After_Tax__c = 10000.00;
        o.Net_YTD_Salary_Annually__c = 10000.00;
        o.Net_YTD_Salary_Monthly__c = 10000.00;
        o.Opportunity__c = Test_DataGeneratorHelper.tstOpportunity.Id;
        o.Pay_Period_Annually__c = 10000.00;
        o.Pay_Period_Monthly__c = 10000.00;
        o.Sales__c = 10000.00;
        o.Self_Employed_Class__c = 'Full-Doc';
        o.Self_Employed_Type__c = 'Trust';
        o.Start_Date__c = Date.valueOf('2020-02-25');
        o.Trustees_Number__c = '1';
        o.Type__c = type;
        
        insert o;
    }
    
    public static void createApplicationEmployment() {
        Application_Employment__c o = new Application_Employment__c();
        o.Applicant__c = '1';
        o.Application__c = Test_DataGeneratorHelper.tstOpportunity.Application__r.Id;
        o.Type__c = 'Second Job';
        
        insert o;
        
        o = new Application_Employment__c();
        o.Applicant__c = '2';
        o.Application__c = Test_DataGeneratorHelper.tstOpportunity.Application__r.Id;
        o.Type__c = 'Second Job';
        
        insert o;
    }
   
}